// Auto-generated by build.js
const articles = [
  {
    "id": 1,
    "title": "Hello World - 我的第一篇博客",
    "date": "2026-05-15",
    "tags": [
      "技术",
      "前端"
    ],
    "summary": "欢迎来到我的博客！这是我的第一篇文章，记录搭建博客的过程。",
    "content": "<p><br><h2>为什么写博客</h2></p><p>一直想有个自己的博客，记录学习和生活。之前用过 WordPress、Hugo，这次想试试最纯粹的方式：纯静态 HTML，一个文件搞定一切。</p><p><h2>技术选型</h2></p><p>最终选择了：</p><p><ul><li>HTML5 + CSS3 + 原生 JavaScript</li></ul><br><ul><li>零 npm 依赖</li></ul><br><ul><li>Cloudflare Pages 部署</li></ul></p><p><h2>Hello World</h2></p><p>这是每程序员的第一步。从这个简单的输出开始，到搭建完整的博客系统，每一步都是学习。</p><p><pre><code class=\"language-javascript\">console.log(\"Hello World!\");<br></code></pre></p><p>期待在这里记录更多有趣的故事。<br></p>",
    "image": "",
    "audio": ""
  }
];
