#!/usr/bin/env node
/**
 * build.js - 从 posts/ 目录读取 Markdown，生成文章数据
 * 用法: node scripts/build.js
 */
const fs = require('fs');
const path = require('path');

const POSTS_DIR = path.join(__dirname, '..', 'posts');
const INDEX_FILE = path.join(__dirname, '..', 'index.html');

function parseFrontMatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) return { meta: {}, body: content };
  
  const meta = {};
  match[1].split('\n').forEach(line => {
    const [key, ...vals] = line.split(':');
    if (key && vals.length) {
      meta[key.trim()] = vals.join(':').trim();
    }
  });
  return { meta, body: match[2] };
}

function mdToHtml(md) {
  let html = md
    // Code blocks
    .replace(/```(\w*)\n([\s\S]*?)```/g, '<pre><code class="language-$1">$2</code></pre>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    // Headings
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    // Bold & italic
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Blockquote
    .replace(/^> (.+)$/gm, '<blockquote><p>$1</p></blockquote>')
    // Unordered list
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    // Images
    .replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" loading="lazy">')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" target="_blank">$1</a>')
    // Paragraphs
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>');

  // Wrap list items
  html = html.replace(/(<li>.*?<\/li>)/gs, '<ul>$1</ul>');
  // Remove nested ul
  html = html.replace(/<\/ul>\s*<ul>/g, '');
  
  return '<p>' + html + '</p>';
}

function build() {
  if (!fs.existsSync(POSTS_DIR)) {
    console.log('No posts/ directory found, skipping build.');
    return;
  }

  const files = fs.readdirSync(POSTS_DIR).filter(f => f.endsWith('.md'));
  const articles = [];

  files.forEach((file, idx) => {
    const raw = fs.readFileSync(path.join(POSTS_DIR, file), 'utf-8');
    const { meta, body } = parseFrontMatter(raw);
    
    articles.push({
      id: idx + 1,
      title: meta.title || file.replace('.md', ''),
      date: meta.date || new Date().toISOString().split('T')[0],
      tags: meta.tags ? meta.tags.split(',').map(t => t.trim()) : [],
      summary: meta.summary || body.substring(0, 100).replace(/[#*>\-]/g, '').trim() + '...',
      content: mdToHtml(body),
      image: meta.image || '',
      audio: meta.audio || ''
    });
  });

  // Sort by date descending
  articles.sort((a, b) => b.date.localeCompare(a.date));

  // Write posts-data.js
  const dataPath = path.join(__dirname, '..', 'posts-data.js');
  fs.writeFileSync(dataPath, `// Auto-generated by build.js\nconst articles = ${JSON.stringify(articles, null, 2)};\n`);
  console.log(`✅ Generated posts-data.js (${articles.length} articles)`);

  // Update index.html
  if (fs.existsSync(INDEX_FILE)) {
    let html = fs.readFileSync(INDEX_FILE, 'utf-8');
    const marker = '// ===== Article Data =====';
    const endMarker = '// ===== State =====';
    const startIdx = html.indexOf(marker);
    const endIdx = html.indexOf(endMarker);
    
    if (startIdx !== -1 && endIdx !== -1) {
      const newData = `${marker}\nconst articles = ${JSON.stringify(articles, null, 2)};\n\n`;
      html = html.substring(0, startIdx) + newData + html.substring(endIdx);
      fs.writeFileSync(INDEX_FILE, html);
      console.log('✅ Updated index.html with new article data');
    }
  }

  console.log(`🎉 Build complete! ${articles.length} articles ready.`);
}

build();
